version: '3'
# 실행명령어
services:
  agree-mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: profileGen
      MYSQL_ROOT_PASSWORD: root
  agree-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
  agree-spring:
    image: agree-spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - agree-mysql
      - agree-redis
    environment:
      MYSQL_URL: jdbc:mysql://agree-mysql:3306/agree
      REDIS_HOST: agree-redis
      REDIS_PORT: 6379
      JWT_SECRET: b9ba604a99274bf89bfafdaf95ae5a9bdasdsafassaf
      SPRING_PROFILES_ACTIVE: local