spring: # test profile
  datasource:
    url: "jdbc:h2:mem:agree;MODE=MYSQL"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # true: [ddl-auto]가 이루어지고, [sql script]가 실행 / false: [sql script]먼저 실행
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis: # redis auto-config ?? (RedisProperties ? ???? ??)
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  sql.init.mode: never # [sql script]를 실행하는지의 여부
logging:
  level.org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
jwt:
  secret: ${JWT_SECRET:b9ba604a99274bf89bfafdaf95ae5a9bdasdsafassaf}
  access-token-expire-time: 1800000 # 30 minutes
  refresh-token-expire-time: 2592000000 # 30 days
server:
  shutdown: immediate
  tomcat:
    connection-timeout: 2s # http 요청을 서버가 수락하기까지의 시간
    keep-alive-timeout: 15s # http 요청을 서버가 수락한 후, 연결이 유지되는 시간
    threads:
      max: 50 # 최대 스레드 수 (default: 200) / 테스트 환경에서는 50으로 설정
      min-spare: 5 # 최소 스레드 수 (default: 10) / 테스트 환경에서는 5로 설정
    accept-count: 100 # 작업 대기열에 들어갈 수 있는 최대 요청 수 (default: 100)
---
spring: # dev profile
  config:
    activate:
      on-profile: dev
  datasource:
#    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/agree?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/agree}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#        userLocalSessionState: true
#        rewriteBatchedStatements: true
#        cacheResultSetMetadata: true
#        cacheServerConfiguration: true
#        elideSetAutoCommits: true
#        maintainTimeStats: false
# ------------ debug ------------
#        profileSQL: true
#        logger: Slf4JLogger
#        maxQuerySizeToLog: 999999
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  sql.init.mode: never
  flyway:
    enabled: true
    fail-on-missing-locations: true # 스크립트 파일을 저장하는 위치를 못 찾을때 실패할지 여부
    baseline-on-migrate: true # Flyway가 초기화되지 않은 데이터베이스에 마이그레이션을 적용할 때 초기 버전으로 마이그레이션 파일을 적용할지 여부
    baseline-version: 1 # Flyway가 초기화되지 않은 데이터베이스에 마이그레이션을 적용할 때 버전을 설정
server:
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 200 # 최대 스레드 수
      min-spare: 10 # 최소 스레드 수