name: Build Docker Image

on: push # push 이벤트가 발생하면 workflow가 실행됩니다.
permissions:
  contents: read # 권한을 설정합니다.
  security-events: write
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bayy1216/agreeassociation
  VERSION: ${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest

    # set up java
    steps:
      - name: Checkout Repository # 저장소를 체크아웃합니다.
        uses: actions/checkout@v4

      - name: Set up JDK 17 # JDK 17을 설정합니다.
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle # Gradle을 설정합니다.
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Build docker image # 도커 이미지를 빌드합니다.
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
      - name: OCI image volunerability scan # OCI 이미지 취약점 스캔
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          security-cutoff: high
          acs-report-enable: true
      - name: Upload scan results # 스캔 결과 업로드
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into container registry # 컨테이너 레지스트리에 로그인합니다.
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to container registry # 컨테이너 레지스트리에 이미지를 푸시합니다.
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}